# Generated by Django 5.1.1 on 2024-12-19 23:09

import django.db.models.deletion
import sentences.validators
from django.conf import settings
from django.db import migrations, models

from ..cedict_ts import mandarin_dict_unstructured
from ..functions import create_dictionary

def run_create_dictionary(apps, schema_editor):
    create_dictionary(mandarin_dict_unstructured)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CEDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional', models.TextField(validators=[sentences.validators.is_traditional])),
                ('simplified', models.TextField(validators=[sentences.validators.is_simplified])),
                ('pronunciation', models.TextField(validators=[sentences.validators.is_pinyin])),
                ('definitions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[sentences.validators.has_chinese])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordsInSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuation', models.TextField(null=True)),
                ('order', models.IntegerField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentences.sentence')),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sentences.cedictionary')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sentence',
            name='words',
            field=models.ManyToManyField(through='sentences.WordsInSentence', to='sentences.cedictionary'),
        ),
        migrations.RunPython(run_create_dictionary),
    ]
