# Generated by Django 5.1.4 on 2025-01-07 22:20

import django.db.models.deletion
from sentences.models import validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CEDictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "traditional",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        validators=[validators.is_traditional],
                    ),
                ),
                (
                    "simplified",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        validators=[validators.is_simplified],
                    ),
                ),
                ("word_length", models.PositiveIntegerField(editable=False)),
                (
                    "pronunciation",
                    models.TextField(validators=[validators.is_pinyin]),
                ),
                ("definitions", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ConstituentHanzi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "hanzi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hanzi_word",
                        to="sentences.cedictionary",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_hanzi",
                        to="sentences.cedictionary",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("word", "hanzi", "order")},
            },
        ),
        migrations.AddField(
            model_name="cedictionary",
            name="hanzi",
            field=models.ManyToManyField(
                related_name="is_in",
                through="sentences.ConstituentHanzi",
                to="sentences.cedictionary",
            ),
        ),
        migrations.CreateModel(
            name="SentenceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentence_id",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("json_data", models.JSONField(unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="cedictionary",
            unique_together={
                (
                    "traditional",
                    "simplified",
                    "word_length",
                    "pronunciation",
                    "definitions",
                )
            },
        ),
    ]
