# Generated by Django 5.1.4 on 2025-01-22 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentences", "0002_alter_sentencehistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentencehistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
