# Generated by Django 5.1.4 on 2025-01-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentences", "0002_populate_dictionary"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentenceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentence_id",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("json_data", models.TextField(unique=True)),
            ],
        ),
    ]
