# Generated by Django 5.1.1 on 2024-10-08 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0003_alter_ecdictionary_pronunciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsinsentence',
            name='punctuation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wordsinsentence',
            name='word',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sentences.ecdictionary'),
        ),
    ]
