# Generated by Django 5.1.1 on 2024-10-08 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0004_wordsinsentence_punctuation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsinsentence',
            name='punctuation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='wordsinsentence',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sentences.ecdictionary'),
        ),
    ]
