# Generated by Django 5.1.1 on 2024-10-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0005_alter_wordsinsentence_punctuation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordsinsentence',
            options={'ordering': ['order']},
        ),
    ]
