# Generated by Django 6.0.4 on 2026-04-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentences", "0006_simplify_reading_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingRoomChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_slug", models.CharField(db_index=True, max_length=100)),
                ("chapter_order", models.IntegerField()),
                ("chapter_number", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("data", models.JSONField()),
            ],
            options={
                "ordering": ["book_slug", "chapter_order"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="readingroomtext",
            name="unique_reading_room_chapter",
        ),
        migrations.RenameIndex(
            model_name="cedefinition",
            new_name="sentences_c_cedict__b07d11_idx",
            old_name="sentences_c_cedict_language_idx",
        ),
        migrations.RenameIndex(
            model_name="cedefinition",
            new_name="sentences_c_languag_a042c4_idx",
            old_name="sentences_c_language_idx",
        ),
        migrations.AlterField(
            model_name="cedictionary",
            name="hanzi",
            field=models.ManyToManyField(
                related_name="is_in",
                through="sentences.ConstituentHanzi",
                through_fields=("word", "hanzi"),
                to="sentences.cedictionary",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="readingroomtext",
            unique_together={("book", "book_order", "chapter_order")},
        ),
        migrations.AlterUniqueTogether(
            name="readingroomchapter",
            unique_together={("book_slug", "chapter_order")},
        ),
    ]
