# Generated by Django 6.0.4 on 2026-04-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sentences", "0007_reading_room_chapter"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReadingRoomText",
        ),
    ]
