# Generated by Django 6.0.4 on 2026-05-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentences", "0008_delete_readingroomtext"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(db_index=True, max_length=50, unique=True)),
                ("pinyin", models.JSONField(default=list)),
                ("definitions_en", models.JSONField(default=list)),
                ("definitions_de", models.JSONField(default=list)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Custom Definition",
                "verbose_name_plural": "Custom Definitions",
                "ordering": ["added_at"],
            },
        ),
    ]
