# Generated by Django 6.0.4 on 2026-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentences", "0009_custom_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="cedictionary",
            name="is_machine_translated",
            field=models.BooleanField(default=False),
        ),
    ]
