# Generated by Django 5.1.4 on 2025-01-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_mandobotuser_delete_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandobotuser",
            name="pronunciation_preference",
            field=models.CharField(
                choices=[
                    ("pinyin_num", "Pinyin_Num"),
                    ("pinyin_acc", "Pinyin_Acc"),
                    ("zhuyin", "Zhuyin"),
                    ("ipa", "Ipa"),
                ],
                default="pinyin_acc",
                max_length=10,
            ),
        ),
    ]
