# Generated by Django 5.1.4 on 2025-01-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_mandobotuser_pronunciation_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandobotuser",
            name="last_payment",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="mandobotuser",
            name="subscription_active",
            field=models.BooleanField(default=True),
        ),
    ]
