# Generated by Django 5.1.4 on 2025-01-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_paidbutunregistered_alter_mandobotuser_last_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="paidbutunregistered",
            name="registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="paidbutunregistered",
            name="registration_id",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="paidbutunregistered",
            name="user_email",
            field=models.TextField(editable=False, unique=True),
        ),
    ]
