# Generated by Django 5.1.4 on 2025-01-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_paidbutunregistered_registered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paidbutunregistered",
            name="emailed",
            field=models.BooleanField(default=False),
        ),
    ]
