# Generated by Django 5.1.4 on 2025-01-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_paidbutunregistered_emailed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandobotuser",
            name="theme_preference",
            field=models.IntegerField(choices=[(0, "dark"), (1, "light")], default=0),
        ),
    ]
