# Generated by Django 5.1.4 on 2025-01-23 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_resetpasswordrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="resetpasswordrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resetpasswordrequest",
            name="reset_token",
            field=models.CharField(
                default="", editable=False, max_length=20, unique=True
            ),
            preserve_default=False,
        ),
    ]
