# Generated by Django 5.1.4 on 2025-01-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_resetpasswordrequest_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resetpasswordrequest",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
