# Generated by Django 6.0.4 on 2026-04-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_resetpasswordrequest_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandobotuser",
            name="user_language",
            field=models.CharField(
                choices=[("en", "English"), ("de", "German")],
                default="en",
                max_length=2,
            ),
        ),
    ]
