from django.test import TestCase

from mandoBot.schemas import ChineseDictionary, MandarinWordSchema, SegmentationResponse
from sentences.functions import is_punctuation

from . import JiebaSegmenter, Segmenter
from ..models import CEDictionary


class SegmentationTests(TestCase):
    def test_find_umlaut(self):
        word = "女"
        result = Segmenter.segment_and_translate(word)
        expected = SegmentationResponse(
            dictionary={
                "女": ChineseDictionary(
                    english=["female / woman / daughter"],
                    pinyin=["nü3"],
                    zhuyin=["ㄋㄩˇ"],
                )
            },
            sentence=[
                MandarinWordSchema(
                    definitions=["female / woman / daughter"],
                    pinyin=["nü3"],
                    word="女",
                    zhuyin=["ㄋㄩˇ"],
                )
            ],
            translation="Women",
        )
        self.assertEqual(result, expected)

    def test_add_defs(self):
        manually_segmented = ["無關大體"]
        bar = Segmenter.add_pronunciations(manually_segmented)
        sentence, dictionary = Segmenter.add_definitions_and_create_dictionary(bar)
        json_sentence = [x.model_dump_json() for x in sentence]
        expected = [
            '{"word":"無關大體","pinyin":["wu2","guan1","da4","ti3"],"zhuyin":["ㄨˊ","ㄍㄨㄢ","ㄉㄚˋ","ㄊㄧˇ"],"definitions":["to have no bearing or influence on the overall situation"]}'
        ]
        word_in_db = CEDictionary.objects.filter(traditional=manually_segmented[0])
        self.assertTrue(word_in_db.exists())
        self.assertEqual(json_sentence, expected)

        for hanzi in manually_segmented[0]:
            self.assertIn(hanzi, dictionary.keys())

    def test_write_file(self):
        foo = [
            "早上",
            "，",
            "我",
            "",
            "靜坐",
            "",
            "了",
            "",
            "一會兒",
            "。",
            "陳",
            "",
            "老",
            "",
            "五",
            "",
            "送",
            "",
            "進",
            "",
            "飯",
            "",
            "來",
            "，",
            "一",
            "",
            "碗",
            "",
            "菜",
            "，",
            "一",
            "",
            "碗",
            "",
            "蒸",
            "",
            "魚",
            "；",
            "這",
            "",
            "魚",
            "",
            "的",
            "",
            "眼睛",
            "，",
            "白",
            "",
            "而且",
            "",
            "硬",
            "，",
            "張",
            "",
            "著",
            "",
            "嘴",
            "，",
            "同",
            "",
            "那",
            "",
            "一夥",
            "",
            "想",
            "",
            "喫",
            "",
            "人",
            "",
            "的",
            "",
            "人",
            "",
            "一樣",
            "。",
            "喫",
            "",
            "了",
            "",
            "幾",
            "",
            "筷",
            "，",
            "滑溜溜",
            "",
            "的",
            "",
            "不知",
            "",
            "是",
            "",
            "魚",
            "",
            "是",
            "",
            "人",
            "，",
            "便",
            "",
            "把",
            "",
            "他",
            "",
            "兜肚連腸",
            "",
            "的",
            "",
            "吐",
            "",
            "出",
            "。",
            "我",
            "",
            "說",
            "「",
            "老",
            "",
            "五",
            "，",
            "對",
            "",
            "大哥",
            "",
            "說",
            "，",
            "我",
            "",
            "悶",
            "",
            "得",
            "",
            "慌",
            "，",
            "想",
            "",
            "到",
            "",
            "園",
            "",
            "裏",
            "",
            "走",
            "",
            "走",
            "。」",
            "老",
            "",
            "五",
            "",
            "不",
            "",
            "答應",
            "，",
            "走",
            "",
            "了",
            "，",
            "停",
            "",
            "一會",
            "，",
            "可",
            "",
            "就",
            "",
            "來",
            "",
            "開",
            "",
            "了",
            "",
            "門",
            "。",
            "我",
            "",
            "也",
            "",
            "不",
            "",
            "動",
            "，",
            "研究",
            "",
            "他們",
            "",
            "如何",
            "",
            "擺佈",
            "",
            "我",
            "；",
            "知道",
            "",
            "他們",
            "",
            "一定",
            "",
            "不肯",
            "",
            "放鬆",
            "。",
            "果然",
            "！",
            "我",
            "",
            "大哥",
            "",
            "引",
            "",
            "了",
            "",
            "一個",
            "",
            "老頭子",
            "，",
            "慢慢",
            "",
            "走",
            "",
            "來",
            "；",
            "他",
            "",
            "滿眼",
            "",
            "兇",
            "",
            "光",
            "，",
            "怕",
            "",
            "我",
            "",
            "看",
            "",
            "出",
            "，",
            "只是",
            "",
            "低頭",
            "",
            "向",
            "",
            "着",
            "",
            "地",
            "，",
            "從",
            "",
            "眼鏡",
            "",
            "橫",
            "",
            "邊",
            "",
            "暗暗",
            "",
            "看",
            "",
            "我",
            "。",
            "大哥",
            "",
            "說",
            "：「",
            "今天",
            "",
            "你",
            "",
            "彷彿",
            "",
            "很",
            "",
            "好",
            "。」",
            "我",
            "",
            "說",
            "「",
            "是",
            "",
            "的",
            "。」",
            "大哥",
            "",
            "說",
            "：「",
            "今天",
            "",
            "請",
            "",
            "何",
            "",
            "先生",
            "",
            "來",
            "，",
            "給",
            "",
            "你",
            "",
            "診",
            "",
            "一",
            "",
            "診",
            "。」",
            "我",
            "",
            "說",
            "「",
            "可以",
            "！」",
            "其實",
            "",
            "我",
            "",
            "豈",
            "",
            "不",
            "",
            "知道",
            "",
            "這",
            "",
            "老頭子",
            "",
            "是",
            "",
            "劊子手",
            "",
            "扮",
            "",
            "的",
            "！",
            "無非",
            "",
            "借",
            "",
            "了",
            "",
            "看脈",
            "",
            "這",
            "",
            "名目",
            "，",
            "揣",
            "",
            "一",
            "",
            "揣",
            "",
            "肥瘠",
            "：",
            "因",
            "",
            "這",
            "",
            "功勞",
            "，",
            "也",
            "",
            "分",
            "",
            "一",
            "",
            "片",
            "",
            "肉",
            "",
            "喫",
            "。",
            "我",
            "",
            "也",
            "",
            "不",
            "",
            "怕",
            "；",
            "雖然",
            "",
            "不",
            "",
            "喫",
            "",
            "人",
            "，",
            "膽子",
            "",
            "卻",
            "",
            "比",
            "",
            "他們",
            "",
            "還",
            "",
            "壯",
            "。",
            "伸",
            "",
            "出",
            "",
            "兩",
            "",
            "個",
            "",
            "拳頭",
            "，",
            "看",
            "",
            "他",
            "",
            "如何",
            "",
            "下手",
            "。",
            "老頭子",
            "",
            "坐",
            "",
            "着",
            "，",
            "閉",
            "",
            "了",
            "",
            "眼睛",
            "，",
            "摸",
            "",
            "了",
            "",
            "好",
            "",
            "一會",
            "，",
            "呆",
            "",
            "了",
            "",
            "好",
            "",
            "一會",
            "；",
            "便",
            "",
            "張",
            "",
            "開",
            "",
            "他",
            "",
            "鬼",
            "",
            "眼睛",
            "",
            "說",
            "：「",
            "不要",
            "",
            "亂",
            "",
            "想",
            "。",
            "靜",
            "",
            "靜",
            "",
            "的",
            "",
            "養",
            "",
            "幾",
            "",
            "天",
            "，",
            "就",
            "",
            "好",
            "",
            "了",
            "。」",
            "不要",
            "",
            "亂",
            "",
            "想",
            "，",
            "靜",
            "",
            "靜",
            "",
            "的",
            "",
            "養",
            "！",
            "養",
            "",
            "肥",
            "",
            "了",
            "，",
            "他們",
            "",
            "是",
            "",
            "自然",
            "",
            "可以",
            "",
            "多",
            "",
            "喫",
            "；",
            "我",
            "",
            "有",
            "",
            "什麼",
            "",
            "好處",
            "，",
            "怎麼",
            "",
            "會",
            "「",
            "好",
            "",
            "了",
            "」？",
            "他們",
            "",
            "這",
            "",
            "羣",
            "",
            "人",
            "，",
            "又",
            "",
            "想",
            "",
            "喫",
            "",
            "人",
            "，",
            "又",
            "",
            "是",
            "",
            "鬼鬼祟祟",
            "，",
            "想",
            "",
            "法子",
            "",
            "遮掩",
            "，",
            "不敢",
            "",
            "直捷",
            "",
            "下手",
            "，",
            "真",
            "",
            "要",
            "",
            "令",
            "",
            "我",
            "",
            "笑",
            "",
            "死",
            "。",
            "我",
            "",
            "忍",
            "",
            "不住",
            "，",
            "便",
            "",
            "放聲",
            "",
            "大",
            "",
            "笑",
            "",
            "起來",
            "，",
            "十分",
            "",
            "快活",
            "。",
            "自己",
            "",
            "曉得",
            "",
            "這",
            "",
            "笑",
            "",
            "聲",
            "",
            "裏面",
            "，",
            "有的是",
            "",
            "義勇",
            "",
            "和",
            "",
            "正氣",
            "。",
            "老頭子",
            "",
            "和",
            "",
            "大哥",
            "，",
            "都",
            "",
            "失",
            "",
            "了",
            "",
            "色",
            "，",
            "被",
            "",
            "我",
            "",
            "這",
            "",
            "勇氣",
            "",
            "正氣",
            "",
            "鎮壓",
            "",
            "住",
            "",
            "了",
            "。",
            "但是",
            "",
            "我",
            "",
            "有",
            "",
            "勇氣",
            "，",
            "他們",
            "",
            "便",
            "",
            "越",
            "",
            "想",
            "",
            "喫",
            "",
            "我",
            "，",
            "沾光",
            "",
            "一點",
            "",
            "這",
            "",
            "勇氣",
            "。",
            "老頭子",
            "",
            "跨",
            "",
            "出",
            "",
            "門",
            "，",
            "走",
            "",
            "不",
            "",
            "多",
            "",
            "遠",
            "，",
            "便",
            "",
            "低聲",
            "",
            "對",
            "",
            "大哥",
            "",
            "說道",
            "：「",
            "趕緊",
            "",
            "喫",
            "",
            "罷",
            "！」",
            "大哥",
            "",
            "點點頭",
            "。",
            "原來",
            "",
            "也",
            "",
            "有",
            "",
            "你",
            "！",
            "這",
            "",
            "一",
            "",
            "件",
            "",
            "大",
            "",
            "發見",
            "，",
            "雖",
            "",
            "似",
            "",
            "意外",
            "，",
            "也",
            "",
            "在",
            "",
            "意",
            "",
            "中",
            "：",
            "合夥",
            "",
            "喫",
            "",
            "我",
            "",
            "的",
            "",
            "人",
            "，",
            "便是",
            "",
            "我",
            "",
            "的",
            "",
            "哥哥",
            "！",
            "喫",
            "",
            "人",
            "",
            "的",
            "",
            "是",
            "",
            "我",
            "",
            "哥哥",
            "！",
            "我",
            "",
            "是",
            "",
            "喫",
            "",
            "人",
            "",
            "的",
            "",
            "人",
            "",
            "的",
            "",
            "兄弟",
            "！",
            "我",
            "",
            "自己",
            "",
            "被",
            "",
            "人",
            "",
            "喫",
            "",
            "了",
            "，",
            "可",
            "",
            "仍然",
            "",
            "是",
            "",
            "喫",
            "",
            "人",
            "",
            "的",
            "",
            "人",
            "",
            "的",
            "",
            "兄弟",
            "！",
        ]
        bar = Segmenter.add_pronunciations(foo)
        sentence, dictionary = Segmenter.add_definitions_and_create_dictionary(bar)

        json_sentence = [x.model_dump_json() for x in sentence]
        with open("output.txt", "w") as file:
            file.write("[" + ",".join(json_sentence) + "]")

    def test_umlaut_pronunciation(self):
        word = ["旅游"]
        pronunciation = Segmenter.add_pronunciations(word)[0].pinyin
        expected = ["lü3", "you2"]
        self.assertEqual(pronunciation, expected)

    def test_pinyin_colon_to_umlaut(self):
        pinyin = "nu:3"
        converted = Segmenter.pinyin_to_zhuyin(pinyin)
        expected = "ㄋㄩˇ"
        self.assertEqual(converted, expected)

    def test_problematic_hanzi(self):
        sentence = "巴賽族"
        result = Segmenter.segment_and_translate(sentence)

        for word in result.dictionary:
            self.assertNotEqual(result.dictionary[word].english, [])
            self.assertNotEqual(result.dictionary[word].pinyin, [])
            self.assertNotEqual(result.dictionary[word].zhuyin, [])

    def test_chengyu(self):
        chengyu = [
            MandarinWordSchema(
                word="分久必合", pinyin=["1"], zhuyin=["A"], definitions=[]
            ),
            MandarinWordSchema(word="，", pinyin=["2"], zhuyin=["B"], definitions=[]),
            MandarinWordSchema(
                word="合久必分", pinyin=["3"], zhuyin=["C"], definitions=[]
            ),
        ]

        expected = [
            MandarinWordSchema(
                word="分久必合合久必分",
                pinyin=["1", ",", "3"],
                zhuyin=["A", ",", "C"],
                definitions=[],
            ),
        ]

        concatenated_chengyu = Segmenter.try_to_concat(chengyu, 0)
        self.assertEqual(expected, concatenated_chengyu)

    def test_concatenated_chengyu_is_found(self):
        chengyu_phrase = "分久必合，合久必分"
        segmented = Segmenter.segment_and_translate(chengyu_phrase)
        expected = [
            "lit. that which is long divided must unify, and that which is long unified must divide (idiom, from 三國演義|三国演义[San1 guo2 Yan3 yi4]) / fig. things are constantly changing"
        ]
        self.assertEqual(segmented.sentence[0].definitions, expected)

    def test_does_not_duplicate_definitions_before_chengyu(self):
        sentence = "話說天下大勢分久必合，合久必分"
        segmented = Segmenter.segment_and_translate(sentence)

        for word in segmented.sentence:
            self.assertEqual(len(word.definitions), 1)

        for hanzi in sentence:
            if not is_punctuation(hanzi):
                self.assertTrue(hanzi in segmented.dictionary)

    def test_choose_most_common_hanzi(self):
        test_hanzi = "上"
        answer = Segmenter.most_frequent_pronunciation(test_hanzi)
        expected = CEDictionary.objects.get(traditional="上", pronunciation="shang4")
        self.assertEqual(expected, answer)

    def test_dictionary_only_includes_single_hanzi(self):
        phrase = "話說天下大勢分久必合，合久必分。"
        sentence = Segmenter.segment_and_translate(phrase)

        for hanzi in sentence.dictionary:
            self.assertEqual(len(hanzi), 1)

    def test_easy_segmentation(self):
        segments = JiebaSegmenter.segment("我来到北京清华大学")
        self.assertEqual(segments, ["我", "来到", "北京", "清华大学"])
