from django.test import TestCase

from mandoBot.schemas import ChineseDictionary, MandarinWordSchema, SegmentationResponse
from sentences.functions import is_punctuation

from . import JiebaSegmenter, Segmenter
from ..models import CEDictionary


class SegmentationTests(TestCase):
    def test_find_umlaut(self):
        word = "女"
        result = Segmenter.segment_and_translate(word)
        expected = SegmentationResponse(
            dictionary={
                "女": ChineseDictionary(
                    english=["female / woman / daughter"],
                    pinyin=["nü3"],
                    zhuyin=["ㄋㄩˇ"],
                )
            },
            sentence=[
                MandarinWordSchema(
                    definitions=["female / woman / daughter"],
                    pinyin=["nü3"],
                    word="女",
                    zhuyin=["ㄋㄩˇ"],
                )
            ],
            translation="Women",
        )
        self.assertEqual(result, expected)

    def test_add_defs(self):
        manually_segmented = ["無關大體"]
        bar = Segmenter.add_pronunciations(manually_segmented)
        sentence, dictionary = Segmenter.add_definitions_and_create_dictionary(bar)
        json_sentence = [x.model_dump_json() for x in sentence]
        expected = [
            '{"word":"無關大體","pinyin":["wu2","guan1","da4","ti3"],"zhuyin":["ㄨˊ","ㄍㄨㄢ","ㄉㄚˋ","ㄊㄧˇ"],"definitions":["to have no bearing or influence on the overall situation"]}'
        ]
        word_in_db = CEDictionary.objects.filter(traditional=manually_segmented[0])
        self.assertTrue(word_in_db.exists())
        self.assertEqual(json_sentence, expected)

        for hanzi in manually_segmented[0]:
            self.assertIn(hanzi, dictionary.keys())

    def test_write_file(self):
        foo = [
            "晚上",
            "總是",
            "睡",
            "不",
            "着",
            "。",
            "凡事",
            "須",
            "得",
            "研究",
            "，",
            "纔",
            "會",
            "明白",
            "。",
            "他們",
            "——",
            "也",
            "有",
            "給",
            "知縣",
            "打枷",
            "過",
            "的",
            "，",
            "也",
            "有",
            "給",
            "紳士",
            "掌",
            "過",
            "嘴",
            "的",
            "，",
            "也",
            "有",
            "衙役",
            "佔",
            "了",
            "他",
            "妻子",
            "的",
            "，",
            "也",
            "有",
            "老子娘",
            "被",
            "債主",
            "逼",
            "死",
            "的",
            "；",
            "他們",
            "那",
            "時候",
            "的",
            "臉色",
            "，",
            "全",
            "沒有",
            "昨天",
            "這麼",
            "怕",
            "，",
            "也",
            "沒有",
            "這麼",
            "兇",
            "。",
            "最",
            "奇怪",
            "的",
            "是",
            "昨天",
            "街",
            "上",
            "的",
            "那個",
            "女人",
            "，",
            "打",
            "他",
            "兒子",
            "，",
            "嘴",
            "裏",
            "說道",
            "：「",
            "老子",
            "呀",
            "！",
            "我",
            "要",
            "咬",
            "你",
            "幾",
            "口",
            "纔",
            "出氣",
            "！」",
            "他",
            "眼睛",
            "卻",
            "看",
            "着",
            "我",
            "。",
            "我",
            "出",
            "了",
            "一",
            "驚",
            "，",
            "遮掩",
            "不住",
            "；",
            "那",
            "青面獠牙",
            "的",
            "一",
            "夥",
            "人",
            "，",
            "便",
            "都",
            "哄笑",
            "起來",
            "。",
            "陳",
            "老",
            "五",
            "趕",
            "上",
            "前",
            "，",
            "硬",
            "把",
            "我",
            "拖",
            "回",
            "家",
            "中",
            "了",
            "。",
            "拖",
            "我",
            "回",
            "家",
            "。",
            "家裏",
            "的",
            "人",
            "都",
            "裝作",
            "不",
            "認識",
            "我",
            "；",
            "他們",
            "的",
            "眼色",
            "，",
            "也",
            "全",
            "同",
            "別人",
            "一樣",
            "。",
            "進",
            "了",
            "書房",
            "，",
            "便",
            "反",
            "扣",
            "上",
            "門",
            "，",
            "宛然",
            "是",
            "關",
            "了",
            "一",
            "隻",
            "雞",
            "鴨",
            "。",
            "這",
            "一",
            "件",
            "事",
            "，",
            "越",
            "教",
            "我",
            "猜",
            "不",
            "出",
            "底細",
            "。",
            "前",
            "幾",
            "天",
            "，",
            "狼子",
            "村",
            "的",
            "佃戶",
            "來",
            "告",
            "荒",
            "，",
            "對",
            "我",
            "大哥",
            "說",
            "，",
            "他們",
            "村",
            "裏",
            "的",
            "一個",
            "大",
            "惡人",
            "，",
            "給",
            "大家",
            "打",
            "死",
            "了",
            "；",
            "幾",
            "個",
            "人",
            "便",
            "挖",
            "出",
            "他",
            "的",
            "心肝",
            "來",
            "，",
            "用",
            "油",
            "煎炒",
            "了",
            "喫",
            "，",
            "可以",
            "壯",
            "壯",
            "膽子",
            "。",
            "我",
            "插",
            "了",
            "一",
            "句",
            "嘴",
            "，",
            "佃戶",
            "和",
            "大哥",
            "便",
            "都",
            "看",
            "我",
            "幾",
            "眼",
            "。",
            "今天",
            "纔",
            "曉得",
            "他們",
            "的",
            "眼光",
            "，",
            "全",
            "同",
            "外面",
            "的",
            "那",
            "夥",
            "人",
            "一模一樣",
            "。",
            "想",
            "起來",
            "，",
            "我",
            "從",
            "頂",
            "上",
            "直",
            "冷",
            "到",
            "腳跟",
            "。",
            "他們",
            "會",
            "喫",
            "人",
            "，",
            "就",
            "未必",
            "不",
            "會",
            "喫",
            "我",
            "。",
            "你",
            "看",
            "那",
            "女人",
            "「",
            "咬",
            "你",
            "幾",
            "口",
            "」",
            "的",
            "話",
            "，",
            "和",
            "一",
            "夥",
            "青面獠牙",
            "人",
            "的",
            "笑",
            "，",
            "和",
            "前天",
            "佃戶",
            "的",
            "話",
            "，",
            "明明",
            "是",
            "暗號",
            "。",
            "我",
            "看",
            "出",
            "他",
            "話",
            "中",
            "全",
            "是",
            "毒",
            "，",
            "笑",
            "中",
            "全",
            "是",
            "刀",
            "，",
            "他們",
            "的",
            "牙齒",
            "，",
            "全",
            "是",
            "白厲厲",
            "的",
            "排",
            "着",
            "，",
            "這",
            "就是",
            "喫",
            "人",
            "的",
            "家伙",
            "。",
            "照",
            "我",
            "自己",
            "想",
            "，",
            "雖然",
            "不",
            "是",
            "惡人",
            "，",
            "自從",
            "踹",
            "了",
            "古",
            "家",
            "的",
            "簿子",
            "，",
            "可",
            "就",
            "難說",
            "了",
            "。",
            "他們",
            "似乎",
            "別",
            "有",
            "心思",
            "，",
            "我",
            "全",
            "猜",
            "不",
            "出",
            "。",
            "況且",
            "他們",
            "一",
            "翻臉",
            "，",
            "便",
            "說",
            "人",
            "是",
            "惡人",
            "。",
            "我",
            "還",
            "記得",
            "大哥",
            "教",
            "我",
            "做",
            "論",
            "，",
            "無論",
            "怎樣",
            "好人",
            "，",
            "翻",
            "他",
            "幾",
            "句",
            "，",
            "他",
            "便",
            "打",
            "上",
            "幾",
            "個",
            "圈",
            "；",
            "原諒",
            "壞人",
            "幾",
            "句",
            "，",
            "他",
            "便",
            "說",
            "「",
            "翻",
            "天",
            "妙手",
            "，",
            "與",
            "眾",
            "不同",
            "」。",
            "我",
            "那里",
            "猜",
            "得到",
            "他們",
            "的",
            "心思",
            "，",
            "究竟",
            "怎樣",
            "；",
            "況且",
            "是",
            "要",
            "喫",
            "的",
            "時候",
            "。",
            "凡事",
            "總",
            "須",
            "研究",
            "，",
            "纔",
            "會",
            "明白",
            "。",
            "古來",
            "時常",
            "喫",
            "人",
            "，",
            "我",
            "也",
            "還",
            "記得",
            "，",
            "可是",
            "不甚",
            "清楚",
            "。",
            "我",
            "翻",
            "開",
            "歷史",
            "一",
            "查",
            "，",
            "這",
            "歷史",
            "沒有",
            "年代",
            "，",
            "歪歪斜斜",
            "的",
            "每",
            "葉",
            "上",
            "都",
            "寫",
            "着",
            "「",
            "仁義道德",
            "」",
            "幾",
            "個",
            "字",
            "。",
            "我",
            "橫豎",
            "睡",
            "不",
            "着",
            "，",
            "仔細",
            "看",
            "了",
            "半夜",
            "，",
            "纔",
            "從",
            "字",
            "縫",
            "裏",
            "看",
            "出",
            "字",
            "來",
            "，",
            "滿",
            "本",
            "都",
            "寫",
            "着",
            "兩",
            "個",
            "字",
            "是",
            "「",
            "喫",
            "人",
            "」！",
            "書",
            "上",
            "寫",
            "着",
            "這",
            "許多",
            "字",
            "，",
            "佃戶",
            "說",
            "了",
            "這",
            "許多",
            "話",
            "，",
            "卻",
            "都",
            "笑吟吟",
            "的",
            "睜",
            "着",
            "怪",
            "眼睛",
            "看",
            "我",
            "。",
            "我",
            "也",
            "是",
            "人",
            "，",
            "他們",
            "想",
            "要",
            "喫",
            "我",
            "了",
            "！",
        ]
        bar = Segmenter.add_pronunciations(foo)
        sentence, dictionary = Segmenter.add_definitions_and_create_dictionary(bar)

        json_sentence = [x.model_dump_json() for x in sentence]
        with open("output.txt", "w") as file:
            file.write("[" + ",".join(json_sentence) + "]")

    def test_umlaut_pronunciation(self):
        word = ["旅游"]
        pronunciation = Segmenter.add_pronunciations(word)[0].pinyin
        expected = ["lü3", "you2"]
        self.assertEqual(pronunciation, expected)

    def test_pinyin_colon_to_umlaut(self):
        pinyin = "nu:3"
        converted = Segmenter.pinyin_to_zhuyin(pinyin)
        expected = "ㄋㄩˇ"
        self.assertEqual(converted, expected)

    def test_problematic_hanzi(self):
        sentence = "巴賽族"
        result = Segmenter.segment_and_translate(sentence)

        for word in result.dictionary:
            self.assertNotEqual(result.dictionary[word].english, [])
            self.assertNotEqual(result.dictionary[word].pinyin, [])
            self.assertNotEqual(result.dictionary[word].zhuyin, [])

    def test_chengyu(self):
        chengyu = [
            MandarinWordSchema(
                word="分久必合", pinyin=["1"], zhuyin=["A"], definitions=[]
            ),
            MandarinWordSchema(word="，", pinyin=["2"], zhuyin=["B"], definitions=[]),
            MandarinWordSchema(
                word="合久必分", pinyin=["3"], zhuyin=["C"], definitions=[]
            ),
        ]

        expected = [
            MandarinWordSchema(
                word="分久必合合久必分",
                pinyin=["1", ",", "3"],
                zhuyin=["A", ",", "C"],
                definitions=[],
            ),
        ]

        concatenated_chengyu = Segmenter.try_to_concat(chengyu, 0)
        self.assertEqual(expected, concatenated_chengyu)

    def test_concatenated_chengyu_is_found(self):
        chengyu_phrase = "分久必合，合久必分"
        segmented = Segmenter.segment_and_translate(chengyu_phrase)
        expected = [
            "lit. that which is long divided must unify, and that which is long unified must divide (idiom, from 三國演義|三国演义[San1 guo2 Yan3 yi4]) / fig. things are constantly changing"
        ]
        self.assertEqual(segmented.sentence[0].definitions, expected)

    def test_does_not_duplicate_definitions_before_chengyu(self):
        sentence = "話說天下大勢分久必合，合久必分"
        segmented = Segmenter.segment_and_translate(sentence)

        for word in segmented.sentence:
            self.assertEqual(len(word.definitions), 1)

        for hanzi in sentence:
            if not is_punctuation(hanzi):
                self.assertTrue(hanzi in segmented.dictionary)

    def test_choose_most_common_hanzi(self):
        test_hanzi = "上"
        answer = Segmenter.most_frequent_pronunciation(test_hanzi)
        expected = CEDictionary.objects.get(traditional="上", pronunciation="shang4")
        self.assertEqual(expected, answer)

    def test_dictionary_only_includes_single_hanzi(self):
        phrase = "話說天下大勢分久必合，合久必分。"
        sentence = Segmenter.segment_and_translate(phrase)

        for hanzi in sentence.dictionary:
            self.assertEqual(len(hanzi), 1)

    def test_easy_segmentation(self):
        segments = JiebaSegmenter.segment("我来到北京清华大学")
        self.assertEqual(segments, ["我", "来到", "北京", "清华大学"])
