# Generated by Django 5.1.4 on 2025-01-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deepl_character_count", models.PositiveIntegerField()),
                ("deepl_character_limit", models.PositiveIntegerField()),
                (
                    "translation_backend",
                    models.CharField(
                        choices=[(0, "deepl"), (1, "argos")], max_length=10
                    ),
                ),
                ("mandobot_response_time", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
