# Generated by Django 5.1.4 on 2025-01-13 18:22

from django.db import migrations, models


def create_initial_status(apps, schema_editor):
    ServerStatus = apps.get_model("status", "ServerStatus")
    ServerStatus.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverstatus",
            name="deepl_character_count",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="serverstatus",
            name="deepl_character_limit",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="serverstatus",
            name="mandobot_response_time",
            field=models.PositiveSmallIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name="serverstatus",
            name="translation_backend",
            field=models.CharField(
                choices=[(0, "deepl"), (1, "argos")], max_length=10, null=True
            ),
        ),
        migrations.RunPython(create_initial_status),
    ]
