# Generated by Django 5.1.4 on 2025-01-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0002_alter_serverstatus_deepl_character_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverstatus",
            name="deepl_character_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="serverstatus",
            name="deepl_character_limit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="serverstatus",
            name="mandobot_response_time",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="serverstatus",
            name="translation_backend",
            field=models.CharField(
                choices=[(0, "deepl"), (1, "argos")], default="argos", max_length=10
            ),
            preserve_default=False,
        ),
    ]
