# Generated by Django 5.1.4 on 2025-01-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0003_alter_serverstatus_deepl_character_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverstatus",
            name="mandobot_response_time",
            field=models.FloatField(default=2.0),
        ),
    ]
